name: Build and Deploy to EC2 (Reusable)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      app_name:
        required: true
        type: string
    secrets:
      EC2_HOST:
        required: true
      EC2_USER:
        required: true
      EC2_SSH_KEY:
        required: true

jobs:
  build-and-deploy:
    runs-on: ec2-runner #ubuntu-latest

    environment:
      name: ${{ inputs.environment }}
      # Optional: Add protection rules in GitHub UI for approval

    steps:
      - name: Checkout Source
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Maven Build
        run: |
          echo "Maven build"
          # cd apps/${{ inputs.app_name }}
          # mvn clean package -DskipTests

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploying ${{ inputs.app_name }} to ${{ inputs.environment }}"
            # bash ~/scripts/deploy-${{ inputs.environment }}.sh
